# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'ddncr'
        repository: 'ecommerce-store'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: Docker@2
      inputs:
        containerRegistry: 'ddncr'
        repository: 'ecommerce-store'
        command: 'push'
        tags: |
          $(tag)
          latest

- stage: Deploy
  displayName: Deploy
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y git
      displayName: Install Git
    - script: |
        git clone https://$(GITHUB_TOKEN)@github.com/ddn-automatization/ecommerce-k8s
        ls
        cd ecommerce-k8s
        sed -i 's/image: ddncr.azurecr.io\/ecommerce-store:latest/image: ddncr.azurecr.io\/ecommerce-store:$(tag)/' ecommerce-store/values.yaml
      displayName: Clone repository and modify file
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - script: |
        ls
      displayName: Show files
    - task: HelmDeploy@0
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: 'Azure para estudiantes(c2b81daf-f6f7-43a0-957b-b330db4beee6)'
        azureResourceGroup: 'ddn-infra-rg'
        kubernetesCluster: 'ddn-infra-aks1'
        command: 'upgrade'
        chartType: 'FilePath'
        chartPath: 'ecommerce-k8s/ecommerce-store'
        releaseName: 'ecommerce-store'
        valueFile: 'ecommerce-k8s/ecommerce-store/values.yaml'
